version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: atividades_postgres
    environment:
      POSTGRES_DB: AtividadesBD
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: atividades_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - "5050:80"
